Vagrant.configure("2") do |config|
  config.vm.define "jumpbox"

  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
    d.remains_running = true
    d.privileged = true
  end

  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
end
