Vagrant.configure("2") do |config|
  config.vm.define "jumpbox"

  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
    d.remains_running = true
    d.privileged = true
    d.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:rw"]
    d.create_args = [
      "--cgroupns=host",
      "--tmpfs=/run",
      "--tmpfs=/run/lock"
    ]
  end

  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
end
